- name: Install Istio
  command: "{{ item }}"
  args:
    chdir: "/root/istio-{{ istio_ver }}"
  with_items:
    - kubectl apply -f install/kubernetes/istio-demo.yaml
  register: install_istio
  ignore_errors: True
- debug:
    var: install_istio.stdout_lines
